### PR TITLE
Fix assert messages

### PR DESCRIPTION
**Pull request by krogla**
PR fixes unit tests fails, due to a different format of assert messages when compiling the code with a new version of Vyper.

### CODE REVIEW

**Comment by skozin** [comment]
I don't think this is a fix that we want:

1. It changes the bytecode of the contract so it would invalidate the audit we have.
2. If we are to convert the dev-only revert messages to the real revert messages, we should remove the `dev:` prefix.
3. I'd say the proper fix would be on the offchain side: either some changes to the test code or a PR to brownie (it brownie internals are somehow broken by the new Vyper compiler).

**Comment by skozin** [comment]
It seems that something's broken with the brownie/solidity/vyper interaction: developer-only error messages still get correctly parsed by brownie when interacting with the `AnchorVault.vy` contract directly; the only situation when the issue manifests is when accessing the contract via the Solidity proxy (`AnchorVaultProxy.sol`).

**Comment by skozin** [comment]
I'd create an issue in the brownie repo (linking to a minimal reproduction repo) and fix this in our test codebase by temporarily removing error message expectations, e.g.:

```py
def test_deposit_eth_fails_on_unexpected_amount(vault, vault_user):
    # FIXME: expect 'dev: unexpected ETH amount sent' revert reason, see eth-brownie#XXXX
    with reverts():
        vault.submit(10**18, TERRA_ADDRESS, '0xab', {'from': vault_user, 'value': 10**18 - 1})
```

**Comment by TheDZhon** [comment]
Outdated

**Pull request closed without merging**
